const KEYBOARD_KEYS = {
  OGRETMEN_BASLATMA_BUTONU: 'ü', // ü

  OGRETMEN_KIRMIZI_TAKIMA_PUAN_VERME_BUTONU: 'ş',
  OGRETMEN_MAVI_TAKIMA_PUAN_VERME_BUTONU: 'ö',

  OYUNCU_KIRMIZI_TAKIM_BUTONU: 'ğ',
  OYUNCU_MAVI_TAKIM_BUTONU: 'p',
};

export default KEYBOARD_KEYS;
